apiVersion: 1
datasources:
  - name: Tempo
    uid: cp-tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: false
    editable: false
    jsonData:
      httpMethod: GET
      tracesToLogsV2:
        datasourceUid: ''
        spanStartTimeShift: '-2m'
        spanEndTimeShift: '2m'
        filterByTraceID: true
        filterBySpanID: true
      nodeGraph:
        enabled: true